param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [string]$BuildDir = $PSScriptRoot,
    [string]$ReleaseSuffix = '',
    [switch]$PassThruVersion
)

$ErrorActionPreference = 'Stop'

function Get-PluginVersion {
    param([string]$Root)

    try {
        $version = git -C $Root tag --points-at HEAD 2>$null | Select-Object -First 1
        if (-not [string]::IsNullOrWhiteSpace($version)) {
            return $version.Trim()
        }
    } catch {
    }

    try {
        $version = git -C $Root rev-parse --short=12 HEAD 2>$null
        if (-not [string]::IsNullOrWhiteSpace($version)) {
            return $version.Trim()
        }
    } catch {
    }

    return 'unknown'
}

function Escape-PascalString {
    param([string]$Value)

    return ([string]$Value).Replace("'", "''")
}

$generatedDir = Join-Path $BuildDir 'generated'
New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null

$version = Get-PluginVersion -Root $ProjectRoot
$releaseSuffixNormalized = [string]$ReleaseSuffix
if (-not [string]::IsNullOrWhiteSpace($releaseSuffixNormalized)) {
    if (-not $releaseSuffixNormalized.StartsWith('-')) {
        $releaseSuffixNormalized = '-' + $releaseSuffixNormalized
    }
    $version += $releaseSuffixNormalized
}

$tokenLimitsCompressed = (
    Get-Content -LiteralPath (Join-Path $BuildDir 'model_token_limits.json') -Raw -Encoding UTF8 |
    ConvertFrom-Json |
    ConvertTo-Json -Depth 100 -Compress
)

$providers = @(
    @{ Key = 'gpt-5';        Model = 'gpt-5';                ApiBase = 'https://api.openai.com/v1/chat/completions';               PurchasePage = 'https://platform.openai.com/account/billing'; AllowCustomModel = $false },
    @{ Key = 'gpt-5-mini';   Model = 'gpt-5-mini';           ApiBase = 'https://api.openai.com/v1/chat/completions';               PurchasePage = 'https://platform.openai.com/account/billing'; AllowCustomModel = $false },
    @{ Key = 'gpt-5-nano';   Model = 'gpt-5-nano';           ApiBase = 'https://api.openai.com/v1/chat/completions';               PurchasePage = 'https://platform.openai.com/account/billing'; AllowCustomModel = $false },
    @{ Key = 'gpt-4o';       Model = 'gpt-4o';               ApiBase = 'https://api.openai.com/v1/chat/completions';               PurchasePage = 'https://platform.openai.com/account/billing'; AllowCustomModel = $false },
    @{ Key = 'gpt-4.1';      Model = 'gpt-4.1';              ApiBase = 'https://api.openai.com/v1/chat/completions';               PurchasePage = 'https://platform.openai.com/account/billing'; AllowCustomModel = $false },
    @{ Key = 'gpt-4.1-mini'; Model = 'gpt-4.1-mini';         ApiBase = 'https://api.openai.com/v1/chat/completions';               PurchasePage = 'https://platform.openai.com/account/billing'; AllowCustomModel = $false },
    @{ Key = 'ollama';       Model = 'glm-4';               ApiBase = 'http://localhost:11434/v1/chat/completions';               PurchasePage = 'pass';                                         AllowCustomModel = $true  },
    @{ Key = 'gemini-flash'; Model = 'gemini-3-flash-preview'; ApiBase = 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions'; PurchasePage = 'https://aistudio.google.com/app/apikey'; AllowCustomModel = $false },
    @{ Key = '__CUSTOM__';   Model = '';                    ApiBase = '';                                                         PurchasePage = '';                                             AllowCustomModel = $true  }
)

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine('// Generated by prepare_installer.ps1')
[void]$builder.AppendLine('procedure InitializeGeneratedInstallerData;')
[void]$builder.AppendLine('begin')
[void]$builder.AppendLine("  GeneratedPluginVersion := '$(Escape-PascalString $version)';")
[void]$builder.AppendLine("  GeneratedModelTokenLimitsJson := '$(Escape-PascalString $tokenLimitsCompressed)';")
[void]$builder.AppendLine("  SetArrayLength(ProviderPresets, $($providers.Count));")

for ($i = 0; $i -lt $providers.Count; $i++) {
    $provider = $providers[$i]
    $allowCustomModel = if ($provider.AllowCustomModel) { 'True' } else { 'False' }
    [void]$builder.AppendLine("  ProviderPresets[$i].Key := '$(Escape-PascalString $provider.Key)';")
    [void]$builder.AppendLine("  ProviderPresets[$i].Model := '$(Escape-PascalString $provider.Model)';")
    [void]$builder.AppendLine("  ProviderPresets[$i].ApiBase := '$(Escape-PascalString $provider.ApiBase)';")
    [void]$builder.AppendLine("  ProviderPresets[$i].PurchasePage := '$(Escape-PascalString $provider.PurchasePage)';")
    [void]$builder.AppendLine("  ProviderPresets[$i].AllowCustomModel := $allowCustomModel;")
}

[void]$builder.AppendLine('end;')

$includePath = Join-Path $generatedDir 'installer_data.iss.inc'
Set-Content -LiteralPath $includePath -Value $builder.ToString() -Encoding utf8

Write-Host "Generated $includePath with version $version"
if ($PassThruVersion) {
    $version
}
